#NUMPY

In [1]:
#install numpy terlebih dahulu ke VS CODE atau secara otomatis di collab.
#cara install numpy dengan cara tulis conda install numpy atau pip install numpy
#setelah itu import numpy ke system dengan cara import numpy as np

In [2]:
 import numpy as np

In [3]:
# NUMPY berfungsi untuk merubah list ke Array
# np.array()
# CONTOH :

a = [1,2,3,4,5]
a
print(type(a))

#merubah list a dari list ke array
#CONTOH :

b = np.array(a)
print(b)
print(type(b))

#contoh lain -> membuat array LANGSUNG dari np.array

d = np.array([10,20,30,40,50])
print(d)
print(type(d))

<class 'list'>
[1 2 3 4 5]
<class 'numpy.ndarray'>
[10 20 30 40 50]
<class 'numpy.ndarray'>


In [4]:
#terlihat list B sudah menjadi numpy array

In [5]:
#membuat array melalui np.arange
c = np.arange(1,21)
print(c)
print(type(c))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
<class 'numpy.ndarray'>


## Hal di atas disebut dengan 1D array

##di bawah ini penjelasan tentang 2D Array

In [6]:
#membuat array 2D/Matrix
#lihat sebearapa banyak kurung siku di awal untuk menentukan jumlah dimensi atau .ndim
#CONTOH :

e = [
     [10,20,30],
    [40,50,60]
]
e = np.array(e)
print(e)
print(type(e))
print(e.ndim)

[[10 20 30]
 [40 50 60]]
<class 'numpy.ndarray'>
2


In [7]:
 #array di atas disebut dengan 2D array karena mempunyai 2 kurung siku dan membuat 2 baris

In [8]:
#Membuat array n-dimens

g = [
     [
     [1,1,1,1,1],
     [2,2,2,2,2],
     [3,3,3,3,3]],
     [
      [4,4,4,4,4],
      [5,5,5,5,5],
      [6,6,6,6,6],
     ]
]
g = np.array(g)
print(g)
print(g.ndim)

[[[1 1 1 1 1]
  [2 2 2 2 2]
  [3 3 3 3 3]]

 [[4 4 4 4 4]
  [5 5 5 5 5]
  [6 6 6 6 6]]]
3


In [9]:
#Pada contoh di atas terlihat ada 3 KURUNG SIKU yang berarti matrix tersebut mempunyai 3Dimensi array

## 1 D array di sebut Vector
## 2 D array di sebut Matrix
## 3 D array di sebut Tensor

##Menentukan shape suatu array

In [10]:
#menentukan shape suatu array dengan menggunakan .shape
#shape berupa ukuran kolom dan baris
#CONTOH :

print(b)
print(b.shape)
# 1D array akan menunjukan (5,) karena berupa vector
print(e)
print(e.shape)
#2D array akan menunjukan (2,3) karena mempunyai 2 BARIS dan 3 KOLOM
print(g)
print(g.shape)
#3D array akan menunjukan ??


[1 2 3 4 5]
(5,)
[[10 20 30]
 [40 50 60]]
(2, 3)
[[[1 1 1 1 1]
  [2 2 2 2 2]
  [3 3 3 3 3]]

 [[4 4 4 4 4]
  [5 5 5 5 5]
  [6 6 6 6 6]]]
(2, 3, 5)


## Kalau 3D array belum tahu cara bacanya

In [11]:
#Menentukan jumlah total elemen suatu array
#.size
# digunakan untuk menunjukan seberapa banyak angka atau character pada array tersebut
#CONTOH :

print(b)
print(b.size)
#menunjukan angka 5, dimana angka tersebut merupakan jumlah character pada array b
print(e)
print(e.size)
#menunjukan angka 6, dimana angka tersebut merupakan jumlah character pada array e
print(g)
print(g.size)
#menunjukan angka 30, dimana angka tersebut merupakan jumlah character pada array g

[1 2 3 4 5]
5
[[10 20 30]
 [40 50 60]]
6
[[[1 1 1 1 1]
  [2 2 2 2 2]
  [3 3 3 3 3]]

 [[4 4 4 4 4]
  [5 5 5 5 5]
  [6 6 6 6 6]]]
30


#Indexing dan Slicing 

In [12]:
#Indexing dan slicing pada suatu array
print(b)
print(b[0:1])
print(b[0:])
print(b[::2])
#Concept nya sama seperti materi week 1 dari mas afif tentang slicing
#dimana i1 = start, i2 = stop-1, i3 = step

[1 2 3 4 5]
[1]
[1 2 3 4 5]
[1 3 5]


In [13]:
#Merubah urutan array 1D dari belakang ke depan (Descending)
#Contoh :

print(b[::-1])

#angka -1 di artikan system akan memulai character paling belakang

[5 4 3 2 1]


In [14]:
#CONTOH SOAL

### Nomor 1

###### Buatlah sebuah array seperti di bawah ini dan tambahkan setiap elemennya dengan 1

### Cara pertama dengan menambahkan bilangan skalar

In [15]:
h = [10,20,30,40,50]

In [16]:
h = np.array(h)
print(h)
print(type(h))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [17]:
print(h+1)
# terlihat seluruh list pada numpy/array h akan bertambah 1 untuk setiap characternya

[11 21 31 41 51]


### Cara Kedua dengan menggunakan special array (np.ones)

In [18]:
i = [10,20,30,40,50]
i = np.array(i)
print(i)
print(type(i))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [19]:
i + np.ones(5)
#membuat seluruh character dalam list di tambah 1

array([11., 21., 31., 41., 51.])

In [20]:
 #np.zeros()
 #digunakan untuk
 #contoh :
np.zeros (3)

#membuatseluruh character menjadi 0

array([0., 0., 0.])

### Nomor 2

###### Buatlah sebuah array seperti di bawah ini dan keluarkan element yang bernilai negatif.

In [21]:
b = [-3,0,-2,-1,2,3,-4]

In [22]:
# Langka pertama buat array

b = np.array(b)
print(b)
print(type(b))

[-3  0 -2 -1  2  3 -4]
<class 'numpy.ndarray'>


In [23]:
 # jika 'b<0' maka hanya akan dilakukan pengecekan apakah element 'b' kurang dari 0  saja.

 b<0

array([ True, False,  True,  True, False, False,  True])

In [24]:
# Pada data di atas terlihat bahwa seluruh element pada b di check 1 per 1.
# outputnya berupa boolean dan menunjukan TRUE atau False saja

In [25]:
# JIKA 'b[b<0]' maka element di 'b' yang kurang dari 0 akan di tampilkan

In [28]:
b[b<0]
b[b>0]

array([2, 3])

##Nomor 3
###Buatlah sebuah array seperti di bawah ini dan keluarkan element yang bernilai positif dan urutkan dari kecil ke besar

In [46]:
c =[10,-8,4,5,-41,7,5,-4]

In [47]:
# Langkah pertama buat arraynya

c1 = np.array(c)
print(c1)
print(type(c1))

[ 10  -8   4   5 -41   7   5  -4]
<class 'numpy.ndarray'>


In [48]:
# Sort element dari bilangan kecil ke besar
# Caranya memakai syntax np.sort(namaarray)

c1 = np.sort(c1)
print(c1)

[-41  -8  -4   4   5   5   7  10]


In [49]:
# lalu buang element yang negatif, karena di minta untuk menujukan angka positif saja.

c1 = c1[c1>0]
print (c1)

[ 4  5  5  7 10]


In [58]:
print(c)
print

[10, -8, 4, 5, -41, 7, 5, -4]
<class 'list'>


In [60]:
#ATAU BISA JUGA DENGAN CARA DIGABUNG LANGSUNG SORT DAN SELECTNYA
c = np.array(c)
print(c)
print(type(c))


[ 10  -8   4   5 -41   7   5  -4]
<class 'numpy.ndarray'>


In [62]:
print(np.sort(c[c>0])[::-1])

[10  7  5  5  4]


##Nomor 4
###Buatlah sebuah array seperti di bawah ini kemudian tumpukan secara horizontal den vertikal satu sama lain

In [63]:
d = [1,2,3,4,5]
e = [6,7,8,9,10]

In [66]:
# Step pertama buat array

d = np.array(d)
print(d)
print(type(d))

e = np.array(e)
print(e)
print(type(e))

[1 2 3 4 5]
<class 'numpy.ndarray'>
[ 6  7  8  9 10]
<class 'numpy.ndarray'>


In [69]:
# STACKING HORIZONTAL -> np.hstack((array1,array2))
# STACKING VERTICAL -> np.vstack((array1,array2))

de_hstack = np.hstack((d,e))
print(de_hstack)

de_vstack = np.vstack((d,e))
print(de_vstack)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


##Nomor 5
###Buatlah sebuah array seperti di bawah ini yang berasal dari 1 deklarasi variable yang sama. Kemudian kalikan array 1 dengan 2 dan kalikan array kedua dengan 3

In [70]:
f = [10,20,30,40,50]

In [71]:
# Ekspektasi output :

#hasil perkalian dengan 2 -> [20,40,60,80,100]
#hasil perkalian dengan 3 -> [30,60,90,120,150]

In [72]:
# LANGKAH PERTAMA buat array

f = np.array(f)
print(f)
print(type(f))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [74]:
f2 = f.copy()
f2
# CARA COPY NUMPY

array([10, 20, 30, 40, 50])

In [75]:
# Kalikan masing2 variable
print(f*2)

print(f2*3)

[ 20  40  60  80 100]
[ 30  60  90 120 150]


##Nomor 6
###Buatlah sebuah array seperti di bawah ini dan hitung total jumlahnya

In [76]:
h = [1,2,3,4,5]
j = [[1,2,3],
     [4,5,6]]

In [78]:
# Ekspektasi Output :
# total nilai h = 15
# total nilai j berdasarkan penjumlahan baris = [6,15]
# total nilai j berdasarkan penjumlahan kolom = [5,7,9]

In [79]:
# buat array

h = np.array(h)
print(h)
print(type(h))

j = np.array(j)
print(j)
print(type(j))

[1 2 3 4 5]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [80]:
print(h,'\n',j)

[1 2 3 4 5] 
 [[1 2 3]
 [4 5 6]]


In [85]:
# Menjumlahkan array h
# .sum()

print('Total nilai h : ',h.sum())

Total nilai h :  15


In [86]:
# menjumlahkan berdasarkan baris
# baris -> axis = 1

print('Total nilai j berdasarkan baris :', j.sum(axis=1))

Total nilai j berdasarkan baris : [ 6 15]


In [88]:
# menjumlahkan berdasarkan kolom
# kolom -> axis = 0

print('total nilai j berdasarkan kolom : ',j.sum(axis=0))

total nilai j berdasarkan kolom :  [5 7 9]


##Nomor 7
###Buatlah sebuah array seperti di bawah ini dan cari nilai min, max dan sum per baris dan kolom

In [133]:
k = [[1,2,3],
     [4,5,6]]

In [98]:
# Langkah pertama buat array

k = np.array(k)
print(k)
print(type(k))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [101]:
# Mencari nilai minimum -> .min()
# Mencari nilai maximum -> .max()
# Mencari nilai total -> .sum()

print('BARIS :')
print('nilai terendah : ', k.min(axis=1))
print('nilai tertinggi : ', k.max(axis=1))
print('nilai total : ', k.sum(axis=1))
print('KOLOM :')
print('nilai terendah : ',k.min(axis=0))
print('nilai tertinggi : ', k.max(axis=0))
print('nilai total : ', k.sum(axis=0))

BARIS :
nilai terendah :  [1 4]
nilai tertinggi :  [3 6]
nilai total :  [ 6 15]
KOLOM :
nilai terendah :  [1 2 3]
nilai tertinggi :  [4 5 6]
nilai total :  [5 7 9]


##Nomor 8
##Buatlah sebuah array seperti di bawah ini 
##dan cari baris kedua dan kolom kedua

In [102]:
n = [[1,2,3],
     [4,5,6],
     [7,8,9]]

In [104]:
# Pertama buat array

n = np.array(n)
print(n)
print(type(n))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [108]:
# cara mencari baris & kolom :
# namaarray [baris,kolom]

print(n[1,1])

5


In [112]:
# Mengambil seluruh baris

print(n[1])
print(n[1,:])

[4 5 6]
[4 5 6]


In [113]:
# mengambil seluruh kolom :

print (n[:,1])

[2 5 8]


In [116]:
#menampilkan kolom secara 2D
# namaarray[:,[indexkolom]]

print(n[:,[2]])

[[3]
 [6]
 [9]]


In [117]:
# Mengambil element secara diagonal ( kiri ke kanan)
# np.diag()
# buka dokumentasi

In [120]:
print(np.diag(n))
# jika setelah n tidak di tulis keterengan maka otomatis system akan mengambil dari kolom 1
print(np.diag(n,k=1))
# jika setelah nama array diberikan keterngan k=1 maka system ambil dari kolom ke 2
print(np.diag(n,k=-1))
# jika setelah nama array diberikan keterngan k=-1 maka system ambil dari sebelum kolom pertama

[1 5 9]
[2 6]
[4 8]


In [123]:
np.diag(np.diag(n))
# Digunakan untuk mengambil nomor secara diagonal namun yg ditampilkan dimensinya sesuai awal

array([[1, 0, 0],
       [0, 5, 0],
       [0, 0, 9]])

In [126]:
# Mengambil element secara diagonal ( kanan ke kiri)
# np.diag(np.fliplr(n))

np.diag(np.fliplr(n))

array([3, 5, 7])

#Nomor 9
##Buatlah sebuah array seperti di bawah ini
dan cari nilai min max dan sum untuk baris kedua dan kolom kedua

In [128]:
m = [[1,2,3],
     [4,5,6],
     [7,8,9]]

In [129]:
#buat array

m = np.array(m)
print(m)
print(type(m))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [139]:
# buat variable yang berisikan baris ke 2
mb = m[1,:]
print(mb)
print(type(mb))


[4 5 6]
<class 'numpy.ndarray'>
<built-in method sum of numpy.ndarray object at 0x7fd9cceb9870>


In [131]:
# buat variable yang berisikan kolom ke 2

In [138]:
mk = m[:,1]
print(mk)
print(type(mk))

[2 5 8]
<class 'numpy.ndarray'>


In [146]:
# BARIS :
print('Nilai Terendah baris ke 2 : ',np.min(mb))
print('Nilai Tertinggi baris ke 2 : ',np.max(mb))
print('Nilai Total baris ke 2 : ',np.sum(mb))

# KOLOM :
print('Nilai Terendah kolom ke 2 : ',np.min(mk))
print('Nilai Tertinggi kolom ke 2 : ',np.max(mk))
print('Nilai Total kolom ke 2 : ',np.sum(mk))

Nilai Terendah baris ke 2 :  4
Nilai Tertinggi baris ke 2 :  6
Nilai Total baris ke 2 :  15
Nilai Terendah kolom ke 2 :  2
Nilai Tertinggi kolom ke 2 :  8
Nilai Total kolom ke 2 :  15


#Nomor 10

#MATPLOTLIB

In [148]:
#Install matplotlib terlebih dahulu
import matplotlib.pyplot as plt    

In [150]:
#Baca gambar dengan menggunakan plt.imread('location_gambar') lalu masukan ke variable
img = plt.imread('car.png')


In [153]:
# Cek ukuran gambar
# .shape
img.shape

# Hasilnya adalah (700,1120) yg berarti gambar tersebut mempunyai 700 baris dan 1120 kolom

2

In [154]:
img.ndim
#Gambar tersebut berupa 2 array

2

In [152]:
# cek total pixel
# .sizez
img.size

784000

In [155]:
# nilai pixel
# img, udah di scalling

img

array([[0.37254903, 0.3529412 , 0.34509805, ..., 0.        , 0.        ,
        0.        ],
       [0.38431373, 0.36078432, 0.34509805, ..., 0.        , 0.        ,
        0.        ],
       [0.3882353 , 0.36078432, 0.34117648, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.08235294, 0.07450981, 0.09411765, ..., 0.0627451 , 0.0627451 ,
        0.06666667],
       [0.07843138, 0.07450981, 0.10588235, ..., 0.06666667, 0.06666667,
        0.06666667],
       [0.05882353, 0.07058824, 0.12156863, ..., 0.07843138, 0.07843138,
        0.07843138]], dtype=float32)

In [157]:
# Memastikan bahwa data berupa array agar bisa di rubah
# np.asarray(namaimage)

img = np.asarray(img)
type(img)

numpy.ndarray

In [ ]:
#Menentukan nilai yang akan di tambahkan ke pixel
#ubah skala 0-1, divide by 255 (highest pixel value)
